#!/bin/bash

#+==========================================================================
# defaults
#+==========================================================================

img_path=/var/lib/libvirt/images/
cd_path=/var/lib/libvirt/images/

ram=1024
cpus=2

# diskType: ide, virtio
disk_type=virtio

# cdType: ide, virtio
cd_type=ide

# netType: e1000, virtio
net_type="virtio"
net_bridge="br0"

base_ifup_script="$(dirname "$(readlink -f "$0")")"/qemu-ifup
base_ifdown_script="$(dirname "$(readlink -f "$0")")"/qemu-ifdown

# actual port used by qemu is 5900 + vncport specified here
vncport=0

if [ -e /etc/apparmor.d/usr.bin.qemu-system-x86_64 ]; then
	apparmor=1
else
	apparmor=0
fi

baloon=1

