#!/bin/bash

#+==========================================================================
# defaults
#+==========================================================================

imgPath=/var/lib/libvirt/images/
cdPath=/var/lib/libvirt/images/

ram=1024
cpus=2
vmname=$(basename "$1")

# diskType: ide, virtio
diskType=virtio

# netType: e1000, virtio
netType=virtio

baseBridgeScript=/root/kvm/qemu-bridge

net_bridge="lan"
net_type="virtio"

