#!/bin/bash

#+==========================================================================
# defaults
#+==========================================================================

imgPath=/var/lib/libvirt/images/
cdPath=/var/lib/libvirt/images/

ram=1024
cpus=2

# diskType: ide, virtio
diskType=virtio

# netType: e1000, virtio
netType=virtio

baseBridgeScript="$(dirname "$(readlink -f "$0")")"/qemu-bridge

net_bridge="br0"
net_type="virtio"

if [ -e /etc/apparmor.d/usr.bin.qemu-system-x86_64 ]; then
	apparmor=1
else
	apparmor=0
fi

