#!/bin/bash
#
# Copyright 2015 Peter Maloney
#
# License: Version 2 of the GNU GPL or any later version
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

device="$1"

# This doesn't come from anywhere else... so just hardcoded it and generate files dynamically
bridge=BRIDGE_NAME

#set > /tmp/bridge.log
#echo "$@" >> /tmp/bridge.log

ip l set "$device" up
brctl addif "$bridge" "$device"

exit $?
